CREATE TABLE IF NOT EXISTS jornadas (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  torneo_id INT UNSIGNED NOT NULL,
  nro INT UNSIGNED NOT NULL,
  nombre VARCHAR(120) NULL,
  fecha DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_jornadas_torneo FOREIGN KEY (torneo_id) REFERENCES torneos(id) ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE KEY uk_jornadas_torneo_nro (torneo_id, nro),
  INDEX idx_jornadas_fecha (fecha)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
